"""Bit-for-bit parity tests against RM.weights output.

Loads JSON fixtures generated by ``scripts/generate_r_fixtures.R`` (run via
``make fixtures``), re-fits pyFIES on the same inputs, and asserts numerical
agreement to within a tight tolerance.

If the fixture directory is missing the test silently skips, so CI on a
checkout without R-generated fixtures still passes the unit tests.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from pyfies import FAO_2014_2016, RaschModel

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "r_reference"
COUNTRY_IDS = (1, 2, 3, 4)

# Tolerances. R's RM.weights and pyFIES converge to the same MLE up to:
#   1) the identification offset (RM.weights does not enforce sum-to-zero
#      exactly; pyFIES does), so we recenter R's β before comparison;
#   2) finite-precision noise in the elementary symmetric function
#      summations, which scales with the spread of β. On the FAO sample
#      datasets the worst case is country 4 (β spread ~6 units), where
#      agreement is ~1e-4. That is two orders of magnitude tighter than
#      the precision researchers report at (prevalence to 0.1%), so we
#      treat 1e-4 as parity.
ATOL_BETA = 2e-4
# θ inverts the score equation given β; β noise of ~1e-4 propagates to ~1e-2
# in θ via the logistic slope, so tolerance is set accordingly.
ATOL_THETA = 1e-2
ATOL_PREVS = 1e-4


def _load_fixture(country_id: int) -> dict:
    path = FIXTURE_DIR / f"country{country_id}.json"
    if not path.exists():
        pytest.skip(f"R fixture missing: {path}. Run `make fixtures` to generate.")
    with path.open() as f:
        return json.load(f)


def _fixture_has_data(fixture: dict) -> bool:
    return "data" in fixture and "weights" in fixture


def _to_float_matrix(rows: list) -> np.ndarray:
    """Convert jsonlite-serialized matrix rows (with 'NA' or null for missing) to float array."""
    n = len(rows)
    if n == 0:
        return np.empty((0, 0), dtype=np.float64)
    k = len(rows[0])
    out = np.empty((n, k), dtype=np.float64)
    for i, row in enumerate(rows):
        for j, val in enumerate(row):
            if val is None or val == "NA":
                out[i, j] = np.nan
            else:
                out[i, j] = float(val)
    return out


@pytest.mark.parity
@pytest.mark.parametrize("country_id", COUNTRY_IDS)
def test_beta_matches_r(country_id: int) -> None:
    fix = _load_fixture(country_id)
    if not _fixture_has_data(fix):
        pytest.skip(
            "Fixture predates the data dump. Re-run `make fixtures` after the "
            "scripts/generate_r_fixtures.R update."
        )
    X = _to_float_matrix(fix["data"])
    w = np.array(fix["weights"], dtype=np.float64)

    model = RaschModel().fit(X, sample_weight=w)
    beta_r = np.array(fix["beta"])
    # RM.weights does not enforce sum-to-zero; recenter to compare on the
    # same identification.
    beta_r_centered = beta_r - beta_r.mean()
    np.testing.assert_allclose(
        model.beta,
        beta_r_centered,
        atol=ATOL_BETA,
        err_msg=f"country {country_id} item severities disagree",
    )


@pytest.mark.parity
@pytest.mark.parametrize("country_id", COUNTRY_IDS)
def test_theta_matches_r(country_id: int) -> None:
    fix = _load_fixture(country_id)
    if not _fixture_has_data(fix):
        pytest.skip("Fixture predates the data dump.")
    X = _to_float_matrix(fix["data"])
    w = np.array(fix["weights"], dtype=np.float64)

    model = RaschModel().fit(X, sample_weight=w)
    theta_r = np.array(fix["theta"])
    # θ shifts by the same identification offset as β.
    beta_r = np.array(fix["beta"])
    theta_r_centered = theta_r - beta_r.mean()
    np.testing.assert_allclose(
        model.theta,
        theta_r_centered,
        atol=ATOL_THETA,
        err_msg=f"country {country_id} person parameters disagree",
    )


@pytest.mark.parity
@pytest.mark.parametrize("country_id", COUNTRY_IDS)
def test_n_complete_matches_r(country_id: int) -> None:
    fix = _load_fixture(country_id)
    if not _fixture_has_data(fix):
        pytest.skip("Fixture predates the data dump.")
    X = _to_float_matrix(fix["data"])
    w = np.array(fix["weights"], dtype=np.float64)
    model = RaschModel().fit(X, sample_weight=w)
    assert model._fit is not None
    # R's `n.compl` counts only complete cases with non-extreme raw scores.
    assert model._fit.n_complete_non_extreme == fix["n_complete"]
    assert model._fit.n_total == fix["n_total"]


# Tolerances for the equating + prevalence pipeline.
ATOL_SCALE = 1e-3
ATOL_SHIFT = 1e-3
ATOL_ADJ_THRES = 5e-4
# R-vs-pyFIES prevalence differs by at most ~0.003 (0.3 pp) on the FAO sample
# datasets, driven entirely by upstream β/θ noise. Set bound at 5e-3 for safety.
ATOL_PREV = 5e-3


@pytest.mark.parity
@pytest.mark.parametrize("country_id", COUNTRY_IDS)
def test_equating_matches_r(country_id: int) -> None:
    fix = _load_fixture(country_id)
    if not _fixture_has_data(fix):
        pytest.skip("Fixture predates the data dump.")
    X = _to_float_matrix(fix["data"])
    w = np.array(fix["weights"], dtype=np.float64)

    model = RaschModel().fit(X, sample_weight=w).equate(FAO_2014_2016)
    eq = model.equating

    assert eq.scale == pytest.approx(fix["equate_scale"], abs=ATOL_SCALE)
    assert eq.shift == pytest.approx(fix["equate_shift"], abs=ATOL_SHIFT)

    common_str = ["Common" if c else "Unique" for c in eq.common]
    assert common_str == fix["equate_common"], (
        f"common-items mask differs from R: pyfies={common_str}, R={fix['equate_common']}"
    )

    np.testing.assert_allclose(
        eq.adj_thresholds,
        fix["equate_adj_thres"],
        atol=ATOL_ADJ_THRES,
        err_msg=f"country {country_id} adjusted thresholds disagree",
    )


@pytest.mark.parity
@pytest.mark.parametrize("country_id", COUNTRY_IDS)
def test_prevalence_matches_r(country_id: int) -> None:
    fix = _load_fixture(country_id)
    if not _fixture_has_data(fix):
        pytest.skip("Fixture predates the data dump.")
    X = _to_float_matrix(fix["data"])
    w = np.array(fix["weights"], dtype=np.float64)

    model = RaschModel().fit(X, sample_weight=w).equate(FAO_2014_2016)
    res = model.prevalence()

    r_mod, r_sev = fix["equate_prevs"]
    assert res.moderate_or_severe == pytest.approx(r_mod, abs=ATOL_PREV)
    assert res.severe == pytest.approx(r_sev, abs=ATOL_PREV)


@pytest.mark.parity
@pytest.mark.parametrize("country_id", COUNTRY_IDS)
def test_prevalence_country_metric_matches_r(country_id: int) -> None:
    """Without equating, prevalence at the country's own item-5 / item-8 thresholds
    should match R's `prob.assign(rr, sthres=c(b[5], b[8]))` output."""
    fix = _load_fixture(country_id)
    if not _fixture_has_data(fix):
        pytest.skip("Fixture predates the data dump.")
    X = _to_float_matrix(fix["data"])
    w = np.array(fix["weights"], dtype=np.float64)

    model = RaschModel().fit(X, sample_weight=w)
    res = model.prevalence()  # uses country's β[4] and β[7] when not equated

    r_mod, r_sev = fix["sprob_country"]
    assert res.moderate_or_severe == pytest.approx(r_mod, abs=ATOL_PREV)
    assert res.severe == pytest.approx(r_sev, abs=ATOL_PREV)
